### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by hypeJunction**

### CODE REVIEW

**Comment by beck24** [comment]
Ooooooh, that's some much needed love 👍

**Comment by hypeJunction** [comment]
I wasn't finished :)

**Comment by hypeJunction** [comment]
Eventually we need to write tests. It's hard to refactor without fear of breaking something.
Could you please take a closer look here: https://github.com/arckinteractive/elgg_solr/pull/37/files#diff-e93c440af885a2ac30d2e08c774a3934R710

What I've done is added friend/friends of, as well as the access list to the index, so we can use inner joins.
My fear is that access level might go out of sync if for whatever reason reindex is not triggered in time.

**Comment by beck24** [comment]
Oops, was excited at documentation :)
Had to pull the trigger!

I saw the friends/friends_of that looks good.

The access changes looked scary, I haven't used solr joins before but I assume you've tested them and they look ok.  Not too much to worry about with regard to reindex triggering, it's triggered on almost every event.  There may be a couple of seconds lag as most of the time the index is deferred to the shutdown event, which means any new relationships/access changes are resolved by then anyway.

**Pull request merged**
